import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/component/Header";
import Footer from "@/component/Footer";
import clickIcon from "../public/assest/images/check-icon.png"
import arrowIcon from "../public/assest/images/arrow-icon.png"
import arrowIconBlue from "../public/assest/images/arrow-icon-blue.svg"
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
    <Header/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
      <div className="bg-blue">
      <div className="container">
        <div className="py-3">
      <p className="text-white fw-bold fs-4">Ondernemingsregister</p>
      <p className="text-white">Lorem ipsum dolor sit amet</p>
        </div>
      </div>
      </div>
      <section className="container mb-3 pb-3">
        <div className="d-flex gap-4 mt-5">
        <div className="check-card">
          <p className="card-check-head">Bestel uw <span className="text-info">KVK </span>uittreksel</p>
          <div className="row">
            <div className="col check-text-conatiner">
              <div>
              <Image src={clickIcon}/>
              <span>Basisgegevens</span>
              </div>
              <div>
              <Image src={clickIcon}/>
              <span>Rechtsvorm</span>
              </div>
              <div>
              <Image src={clickIcon}/>
              <span>Inschrijfnummer</span>
              </div>
              <div>
              <Image src={clickIcon}/>
              <span>Activiteiten</span>
              </div>
            </div>
            <div className="col check-text-conatiner"><div>
              <Image src={clickIcon}/>
              <span>Bestuurders</span>
              </div>
              <div>
              <Image src={clickIcon}/>
              <span>Kapitaal</span>
              </div>
              <div>
              <Image src={clickIcon}/>
              <span>Datum van oprichting</span>
              </div>
              <div>
              <Image src={clickIcon}/>
              <span>Historische informatie</span>
              </div></div>

          </div>
          <p className="card-p mt-3">Zoek op KVK-nummer of bedrijfsnaam en ontvang direct uw KVK uittreksel.</p>
          <div className=""><input className="py-3 w-50 px-2" placeholder="Zoek op naam of KVK-nummer"/><button className="card-btn">Zoeken</button></div>
        </div>
        <div className="check-card">
          <p className="card-check-head">Haal uw<span className="text-info"> BTW</span>-nummer op</p>
          <div className="row">
            <div className="check-text-conatiner">
              <div>
              <span>Waarvoor wordt het BTW-nummer gebruikt?</span>
              </div>
              <div>
              <Image src={clickIcon}/>
              <span>Handel binnen de EU</span>
              </div>
              <div>
              <Image src={clickIcon}/>
              <span>Aangifte doen</span>
              </div>
              <div>
              <Image src={clickIcon}/>
              <span>Activiteiten</span>
              </div>
            </div>
          </div>
          <p className="card-p mt-3">Zoek op KVK-nummer of bedrijfsnaam en ontvang direct uw KVK uittreksel.</p>
          <div className=""><input className="py-3 w-50 px-2" placeholder="Zoek op naam of KVK-nummer"/><button className="card-btn">Zoeken</button></div>
        </div>
        </div>
      </section>
      <section  className="container mt-5 home-section2">
      <div className="row">
      <div className="col-9 padding-right">
      <h1 className="card-check-head mb-5">Bestel uw <span className="text-info">KVK </span>uittreksel</h1>
       <div className="">
        <h3>Wat doet MijnUittreksels.nl?</h3>
        <p>Op MijnUittreksels.nl kunt u gemakkelijk zoeken op bedrijfsnaam en voor het gewenste bedrijf het KVK uittreksel aanvragen. MijnUittreksels is een intermediair voor het aanvragen van KVK uittreksels. Ontvang zonder in te loggen en na de betaling direct uw uittreksel in uw mailbox.</p>
       </div>
       </div>
       <div className="small-card bg-blue col-3 d-flex flex-column justify-content-evenly">
        <span className="text-white">Digitaal gewaarmerkt uittreksel</span>
        <p className="text-white">
        Direct bestellen <span>
        <Image src={arrowIcon} />
        </span>
        </p>
       </div>
      </div>  
      <div className="row mt-5">
      <div className="col-9 padding-right">
       <div className="">
        <h3>Wat is een KVK uittreksel?</h3>
        <p>Een KVK uittreksel verwijst naar een document dat wordt verstrekt door de Kamer van Koophandel (KVK) in Nederland. De KVK is een instantie die verantwoordelijk is voor het bijhouden van het handelsregister van ondernemingen in Nederland. Een KVK uittreksel
is een officieel document dat informatie bevat over een geregistreerde onderneming, zoals een bedrijf, eenmanszaak, vennootschap, stichting, vereniging, enzovoort. Dit uittreksel bevat belangrijke informatie over de onderneming, zoals:</p>
       </div>
       </div>
       <div className="small-card bg-blue col-3 d-flex flex-column justify-content-evenly">
        <span className="text-white">Niet gewaarmerkt
uittreksel</span>
        <p className="text-white">
        Direct bestellen <span>
        <Image src={arrowIcon} />
        </span>
        </p>
       </div>
      </div>    
      <div className="row align-items-end mt-5">
      <div className="col-9 padding-right">
       <div className="">
        <p><strong>Basisgegevens:</strong> Dit omvat de naam van de onderneming, het adres van de vestiging, en andere identificerende informatie.</p>
        <p><strong>Rechtsvorm:</strong> Het type juridische structuur van de onderneming, bijvoorbeeld BV (Besloten Vennootschap), Eenmanszaak, NV (Naamloze Vennootschap), etc.</p>
        <p><strong>Inschrijfnummer:</strong> Een uniek nummer dat aan de onderneming is toegewezen bij
registratie.</p>
        <p><strong>Activiteiten:</strong> De aard van de activiteiten die de onderneming uitvoert.</p>
        <p><strong>Bestuurders:</strong> De namen van de bestuurders, directieleden of eigenaren van de onderneming.</p>
        <p><strong>Kapitaal:</strong> Voor ondernemingen met aandelenkapitaal wordt informatie over het aandelenkapitaal vermeld.</p>
        <p><strong>Datum van oprichting:</strong>  De datum waarop de onderneming is opgericht</p>
        <p><strong>Historische informatie:</strong> Eventueel voorgaande wijzigingen, zoals adreswijzigingen, bestuurswijzigingen, of wijzigingen in de bedrijfsactiviteiten.<br/>Een KVK uittreksel wordt vaak gebruikt voor verschillende zakelijke doeleinden, zoals
bij het aangaan van zakelijke relaties, het aanvragen van financiering, het aangaan van contracten, het verifiëren van de bedrijfsinformatie, en meer. Het is een manier om betrouwbare en officiële informatie over een onderneming te verkrijgen.</p>
       </div>
       </div>
       <div className="small-card border-blue py-4 bg-white col-3 d-flex flex-column justify-content-between">
        <span className="text-blue">Vragen?</span>
        <p className="text-blue">
        Neem contact op <span>
        <Image src={arrowIconBlue} className="text-blue" />
        </span>
        </p>
       </div>
      </div>    
      </section>
      <section className="container home-section2">
      <div className="row">
      <div className="col-9 padding-right">
      <h1 className="card-check-head mb-5">Haal uw <span className="text-info">BTW</span>-nummer op</h1>
       <div className="">
        <h3>Wat is een BTW-nummer?</h3>
        <p>Het BTW-nummer is een unieke identificatiecode voor bedrijven binnen de Europese
Unie die betrokken zijn bij transacties waarbij BTW (Belasting Toegevoegde Waarde) in
rekening wordt gebracht. Dit nummer is essentieel voor de administratie van BTW en het
faciliteren van handel tussen EU-landen.</p>
       </div>
       </div>
       <div className="small-card bg-blue col-3 d-flex flex-column justify-content-evenly">
        <span className="text-white">Digitaal gewaarmerkt uittreksel</span>
        <p className="text-white">
        Direct bestellen <span>
        <Image src={arrowIcon} />
        </span>
        </p>
       </div>
      </div>  
      <div className="row mt-5">
      <div className="col-9 padding-right">
       <div className="">
        <h3>Structuur van het BTW-nummer</h3>
        <p>Het BTW-nummer heeft in elk EU-land een specifieke structuur, maar begint altijd met
een landcode bestaande uit twee letters, gevolgd door een reeks cijfers of letters.
Bijvoorbeeld in Nederland begint het BTW-nummer met de landcode "NL" gevolgd door
een combinatie van cijfers en letters.</p>
       </div>
       </div>
       {/* <div className="small-card bg-blue col-3 d-flex flex-column justify-content-evenly">
        <span className="text-white">Niet gewaarmerkt
uittreksel</span>
        <p className="text-white">
        Direct bestellen <span>
        <Image src={arrowIcon} />
        </span>
        </p>
       </div> */}
      </div>    
      <div className="row align-items-end mt-5">
      <div className="col-9 padding-right">
       <div className="">
        <h3>Waarvoor wordt het BTW-nummer gebruikt?</h3>
        <p><strong>Handel binnen de EU:</strong> Bij transacties tussen bedrijven uit verschillende EU-landen is het BTW-nummer nodig om de BTW correct te kunnen verrekenen.</p>
        <p><strong>Aangifte doen:</strong> Bedrijven gebruiken hun BTW-nummer bij het indienen van BTW-
aangiften.</p>
        <p><strong>Facturering:</strong> Het BTW-nummer moet op facturen worden vermeld, zodat zowel
kopers als verkopers de transactie kunnen documenteren voor hun administratie.</p>
       </div>

       <div className="mt-5 pt-4">
        <h3>Hoe verschilt het BTW-nummer van het RSIN/FI-nummer?</h3>
        <p>In Nederland wordt het BTW-nummer soms verward met het RSIN (Rechtspersonen en
Samenwerkingsverbanden Informatie Nummer) of FI-nummer (Fiscaal
Identificatienummer). Hoewel het RSIN/FI-nummer ook wordt gebruikt voor fiscale
doeleinden, is het BTW-nummer specifiek bedoeld voor transacties die betrekking
hebben op de BTW.</p>
       </div>
       <div className="mt-5 pt-4">
        <h3>Belangrijk om te weten:</h3>
        <p>Het is essentieel dat bedrijven hun BTW-nummer correct en consistent gebruiken, vooral
wanneer ze zaken doen met andere EU-landen. Een onjuist gebruik kan leiden tot
boetes en andere fiscale complicaties.</p>
       </div>
       </div>
       <div className="small-card border-blue py-4 bg-white col-3 d-flex flex-column justify-content-between">
        <span className="text-blue">Vragen?</span>
        <p className="text-blue">
        Neem contact op <span>
        <Image src={arrowIconBlue} className="text-blue" />
        </span>
        </p>
       </div>
      </div>    
      </section>
      <section id="section4" className="container bg-blue">
        <div className="d-flex flex-column">
          <p className="text-white">Lorem ipsum dolor sit amet. <br/>
Sit facere illo quo earum Quis non unde animi est eaque repellat et <br/>
accusantium corporis est similique odit in nobis error.</p>
<button className="bg-white text-blue mx-auto fw-bold border border-white px-4 py-2 mt-4">Direct bestellen</button>
        </div>
      </section>
      </main>
      <Footer/>
    </>
  );
}
